builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
      - -tags="netgo"
    ldflags:
      - >-
          -s
          -w
          -X main.Version={{ .Tag }}
          -X main.Commit={{ .Commit }}
          -X main.BuildTime={{ .Date }}

kos:
  - repository: ghcr.io/janfuhrer/podsalsa
    tags:
      - '{{.Tag}}'
      - '{{ if not .Prerelease }}latest{{ end }}'
    bare: true
    preserve_import_paths: false
    sbom: none
    platforms:
      - all
    flags:
      - -trimpath
      - -tags="netgo"
    ldflags:
      - >-
          -s
          -w
          -X main.Version={{ .Tag }}
          -X main.Commit={{ .Commit }}
          -X main.BuildTime={{ .Date }}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^rebase:'
      - Merge pull request
