project_name: podsalsa

before:
  hooks:
    - go mod tidy

builds:
  - id: podsalsa
    binary: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    # set for reproducible builds
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
      - -tags="netgo"
    ldflags:
      - >-
          -s
          -w
          -X main.Version={{ .Tag }}
          -X main.Commit={{ .Commit }}
          -X main.BuildTime={{ .Date }}

kos:
  - id: podsalsa
    build: podsalsa
    repository: ghcr.io/janfuhrer/podsalsa
    tags:
      - '{{.Tag}}'
      - '{{ if not .Prerelease }}latest{{ end }}'
    # use default base image
    base_image: cgr.dev/chainguard/static
    labels:
      org.opencontainers.image.created: '{{ .Date }}'
      org.opencontainers.image.authors: "janfuhrer@mailbox.org"
      org.opencontainers.image.url: "https://github.com/janfuhrer/podsalsa"
      org.opencontainers.image.documentation: "https://github.com/janfuhrer/podsalsa"
      org.opencontainers.image.source: "https://github.com/janfuhrer/podsalsa"
      org.opencontainers.image.version: '{{ .Tag }}'
      org.opencontainers.image.revision: '{{ .Commit }}'
      org.opencontainers.image.vendor: "janfuhrer"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.title: "Podsalsa"
      org.opencontainers.image.description: "Sample application to demonstrate supply chain security."
      org.opencontainers.image.base.name: "cgr.dev/chainguard/static"
    # use the docker tag without anything additional
    bare: true
    preserve_import_paths: false
    sbom: cyclonedx # or spdx
    platforms:
      # linux/amd64 and linux/arm64
      - all
    # set for reproducible builds
    creation_time: '{{ .CommitTimestamp }}'
    ko_data_creation_time: '{{.CommitTimestamp}}'

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

# create sboms for the archives
sboms:
  - artifacts: archive

# create checksum file for the archives
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# sign the artifacts
#signs:
#  - artifacts: checksum
#docker_signs:
#  - artifacts: manifests

# local build
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# github changelog for new release
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^rebase:'
      - Merge pull request
