services:
  podsalsa:
    image: ghcr.io/janfuhrer/podsalsa:latest
    container_name: podsalsa
    user: '65532'
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PODSALSA_LEVEL=debug
