// Policy for the SLSA v1 build provenance of the podsalsa container images,
// as generated by GitHub Artifact Attestations (actions/attest-build-provenance).
//
// `gh attestation verify` already proves who signed the provenance. This policy
// covers the complementary question: whether the contents of the provenance
// describe a build we are willing to trust.
//
// Validate a statement against it with:
//
//   gh attestation verify oci://$IMAGE \
//     --repo janfuhrer/podsalsa \
//     --signer-workflow janfuhrer/podsalsa/.github/workflows/build-image.yml \
//     --format json --jq '.[0].verificationResult.statement' > statement.json
//
//   cue vet policy.cue statement.json

// The predicate must be SLSA v1 build provenance.
predicateType: "https://slsa.dev/provenance/v1"

predicate: {
	buildDefinition: {
		// The provenance must describe a GitHub Actions workflow run.
		buildType: "https://actions.github.io/buildtypes/workflow/v1"

		externalParameters: {
			workflow: {
				// The release must be built from a version tag ...
				ref: =~"^refs/tags/v[0-9]+\\.[0-9]+\\.[0-9]+(-rc\\.[0-9]+)?$"
				// ... in this source repository ...
				repository: "https://github.com/janfuhrer/podsalsa"
				// ... entered through the release workflow.
				path: ".github/workflows/release.yml"
			}
		}

		internalParameters: {
			github: {
				// Releases must come from GitHub-hosted runners. A self-hosted
				// runner would weaken the build environment guarantees.
				runner_environment: "github-hosted"
			}
		}
	}

	runDetails: {
		builder: {
			// The trusted builder: the reusable workflow that ran the build and
			// signed this provenance. This is the SLSA Build L3 isolation
			// boundary, because release.yml cannot influence what it does.
			id: =~"^https://github.com/janfuhrer/podsalsa/\\.github/workflows/build-image\\.yml@refs/tags/v[0-9]+\\.[0-9]+\\.[0-9]+(-rc\\.[0-9]+)?$"
		}
	}
}
