apiVersion: apps/v1
kind: Deployment
metadata:
  name: podsalsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podsalsa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podsalsa
    spec:
      containers:
      - image: v0.4.1@sha256:ff954525227a38ec863328f3d8c974cdcb3997ac038e29df3b0c4151d878a712
        name: podsalsa
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        livenessProbe:
          failureThreshold: 5
          successThreshold: 1
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
          timeoutSeconds: 10
          initialDelaySeconds: 5
        readinessProbe:
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
          timeoutSeconds: 5
          initialDelaySeconds: 5
        ports:
        - containerPort: 8080
          name: http
        imagePullPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
