apiVersion: apps/v1
kind: Deployment
metadata:
  name: podsalsa-fail
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podsalsa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podsalsa
    spec:
      containers:
      - image: ghcr.io/janfuhrer/podsalsa:v0.1.0@sha256:91bda05305b8ba6ef6a2494d02e409a6968de008b09f77fb0c9c8dcc3f24054e
        imagePullPolicy: Always
        name: podsalsa
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 8080
          name: http
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
