apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30081
    hostPort: 30081
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker
