args:
  cron: 0 30 * * * *
  dtrack-base-url: https://dependency-track.example.com
  format: cyclonedx
  kubernetes-cluster-id: clustername
  targets: dtrack
  verbosity: info
envVars:
- name: SBOM_DTRACK_API_KEY
  valueFrom:
    secretKeyRef:
      key: accessToken
      name: sbom-operator
