command = ["go", "mod", "tidy", "&&", "CGO_ENABLED=0", "GOOS=linux", "GOARCH=amd64", "go", "build", "-trimpath", "-tags=netgo", "-ldflags=-s -w", "-o", "podsalsa"]
#go mod tidy
#RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETPLATFORM} go build \
#  -trimpath \
#  -tags="netgo" \
#  -ldflags "-s -w -X main.Version=${VERSION} -X main.Commit=${COMMIT_REF} -X main.CommitDate=${BUILD_DATE}" \
#  -o podsalsa

artifact_path =  "./podsalsa"
