apiVersion: apps/v1
kind: Deployment
metadata:
  name: podsalsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podsalsa
  template:
    metadata:
      labels:
        app: podsalsa
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: podsalsa
        image: ghcr.io/janfuhrer/podsalsa:v0.3.12@sha256:e111e800dc80067d56499fe10fe1cc90eaf9e204658475b838cbad3db32cdff9
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 8080
        env:
        - name: PODSALSA_LEVEL
          value: "debug"
