apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podsalsa
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: podsalsa
