name: "Gosec Security Scan"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions: {}

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - id: checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false
      - name: Run Gosec Security Scanner
        uses: securego/gosec@3b23ec8f0902ac0438a16fb2e5032202853e7122 # master (since go 1.22.2 is not supported yet)
        env:
          # fix: 1.22.2 is not supported yet
          GOTOOLCHAIN: "go1.22.0"
        with:
          args: ./...
