name: "Gosec Security Scan"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - id: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          persist-credentials: false
      - name: Run Gosec Security Scanner
        uses: securego/gosec@b633c4c0ec489dfc2f4930bb96237371058cb199 # master (since go 1.22.2 is not supported yet)
        env:
          # fix: 1.22.2 is not supported yet
          GOTOOLCHAIN: "go1.22.0"
        with:
          args: ./...
